### ISSUE TITLE
nanofilt failed to filter data

### ISSUE THREAD

**Issue by maculatus** [wdecoster/nanofilt#36]
Hello,
I am using the last version of nanofilt but it is failing to filter the data. I used this:

>cat flog4_20190830.fastq | NanoFilt -l 500 --maxlength 5070 -q 9 

Traceback (most recent call last):
  File "/home/gustavo/anaconda3/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/home/gustavo/anaconda3/lib/python3.6/site-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
ImportError: cannot import name 'process_summary'

**Comment by wdecoster** [comment]
Thanks for reporting this, how did you install NanoFilt?

**Comment by maculatus** [comment]
Using pip install nanofilt
pip 18.1 (python 3.6)

**Comment by maculatus** [comment]
I had also nanopack (pip install nanopack). All the programs resptond to --hep with the exception of NanoFilt and NanoSplit

>NanoFilt --help
Traceback (most recent call last):
  File "/home/gustavo/anaconda3/bin/NanoFilt", line 7, in <module>
    from nanofilt.NanoFilt import main
  File "/home/gustavo/anaconda3/lib/python3.6/site-packages/nanofilt/NanoFilt.py", line 29, in <module>
    from nanoget import process_summary
ImportError: cannot import name 'process_summary'

>NanoSplit --help
Traceback (most recent call last):
  File "/home/gustavo/anaconda3/bin/NanoSplit", line 7, in <module>
    from nanosplit.NanoSplit import main
  File "/home/gustavo/anaconda3/lib/python3.6/site-packages/nanosplit/NanoSplit.py", line 13, in <module>
    from nanomath import aveQual
ImportError: cannot import name 'aveQual'

**Comment by wdecoster** [comment]
Please try pip install again, and see if the version is v2.5.0 (the latest version on PyPI) or older. You may have to add --no-cache-dir to pip install. v2.5.0 does not use process_summary from nanoget anymore, so the error message suggests that yours is older.

NanoSplit is indeed outdated, so that error is expected. I can fix it, but I was not aware that people were still using it.

**Comment by maculatus** [comment]
Hello,
I remove the NanoFilt and it was version 2.2.0. I reinstalled and now it is
2.5.0 and it is working. Many Thanks!
Gustavo
