### ISSUE TITLE
Nanostat question

### ISSUE THREAD

**Issue by valentinavan** [wdecoster/nanofilt#56]
Hi, I applied a quality trimming:
NanoFilt PATH/FILE.fastq -q 10 > highQuality_BA0.fastq 
and I was expecting to find in the new NanoPlot report only the reads above Q10 instead I can still see Q5 and Q7 (report on the left side). What am I not understanding?
<img width="1288" alt="Screen Shot 2022-02-08 at 5 00 02 PM" src="https://user-images.githubusercontent.com/63851352/152943228-fdf22e41-2bb0-43b9-815c-224d75a77d98.png">

I get this error but it can still produce all the plots:

Thanks
```
NanoPlot -t 2 --fastq PATH/highQuality_BA0.fastq --verbose    

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2022-02-08 16:35:35,247 NanoPlot 1.39.0 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', colormap='Greens', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['/Users/linnaeus/highQuality_BA0.fastq'], fastq_minimal=None, fastq_rich=None, feather=None, font_scale=1, format='png', hide_stats=False, huge=False, info_in_report=False, legacy=None, listcolormaps=False, listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, no_static=False, no_supplementary=False, outdir='.', path='./', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=2, title=None, tsv_stats=False, ubam=None, verbose=True)
2022-02-08 16:35:35,247 Python version is: 3.8.8 (default, Feb 24 2021, 13:46:16)  [Clang 10.0.0 ]
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2022-02-08 16:36:22,245 Nanoget: Gathered all metrics of 330588 reads
2022-02-08 16:36:22,379 Calculated statistics
2022-02-08 16:36:22,380 Using sequenced read lengths for plotting.
2022-02-08 16:36:22,391 NanoPlot:  Valid color #4CB391.
2022-02-08 16:36:22,392 NanoPlot:  Valid colormap Greens.
2022-02-08 16:36:22,408 NanoPlot:  Creating length plots for Read length.
2022-02-08 16:36:22,409 NanoPlot:  Using 330588 reads maximum of 31841bp.
2022-02-08 16:36:23,713 Saved ./WeightedHistogramReadlength  as png (or png for --legacy)
2022-02-08 16:36:24,325 Saved ./WeightedLogTransformed_HistogramReadlength  as png (or png for --legacy)
2022-02-08 16:36:24,910 Saved ./Non_weightedHistogramReadlength  as png (or png for --legacy)
2022-02-08 16:36:25,495 Saved ./Non_weightedLogTransformed_HistogramReadlength  as png (or png for --legacy)
2022-02-08 16:36:26,701 Saved ./Yield_By_Length  as png (or png for --legacy)
2022-02-08 16:36:26,703 Created length plots
2022-02-08 16:36:26,723 NanoPlot: Creating Read lengths vs Average read quality plots using 330588 reads.
2022-02-08 16:36:27,928 Saved ./LengthvsQualityScatterPlot_dot  as png (or png for --legacy)
2022-02-08 16:36:29,483 Saved ./LengthvsQualityScatterPlot_kde  as png (or png for --legacy)
2022-02-08 16:36:29,486 Created LengthvsQual plot
2022-02-08 16:36:29,486 Writing html report.
2022-02-08 16:36:29,489 'PandasArray' object has no attribute '_str_strip'
Traceback (most recent call last):
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 110, in main
    make_report(plots, settings)
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 384, in make_report
    report.html_stats(settings),
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/report.py", line 45, in html_stats
    stats_html.append(stats2html(statsfile[0]))
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/report.py", line 51, in stats2html
    values = df["value"].str.strip().str.replace('\t', ' ').str.split().replace(np.nan, '')
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 101, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 1800, in strip
    result = self._data.array._str_strip(to_strip)
AttributeError: 'PandasArray' object has no attribute '_str_strip'

If you read this then NanoPlot 1.39.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 110, in main
    make_report(plots, settings)
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 384, in make_report
    report.html_stats(settings),
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/report.py", line 45, in html_stats
    stats_html.append(stats2html(statsfile[0]))
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/nanoplot/report.py", line 51, in stats2html
    values = df["value"].str.strip().str.replace('\t', ' ').str.split().replace(np.nan, '')
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 101, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/linnaeus/opt/anaconda3/envs/bioinfo/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 1800, in strip
    result = self._data.array._str_strip(to_strip)
AttributeError: 'PandasArray' object has no attribute '_str_strip'
```

**Comment by wdecoster** [comment]
The filtering did work. In the report on the right, 81% of your reads are > Q10. After filtering in the report on the left all reads are > Q10 (100%). If a read is >Q10 then it is also >Q5 :-)

The error from NanoPlot is when the report was being written, so you will indeed have all plots already at that point. Could it be that your pandas version is really old?

Wouter

**Comment by valentinavan** [comment]
Oups...my bad.
